language: php

php:    
  - 7.1

before_script:  
  - cp .env.travis .env  - composer self-update  
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction  

script:
  - vendor/bin/phpunit

notifications:
  email:
    - felipeguimaraes540@gmail.com
    